{% set name = "osfclient" %}
{% set version = "0.0.5" %}
{% set sha256 = "47c92bbdce57ecc0ed87eabe459025cc549080c48b28ebc86bfc5d82545a75c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - osf = osfclient.__main__:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - requests
    - tqdm
    - six

test:
  commands:
    - osf --help
  imports:
    - osfclient

about:
  home: http://osfclient.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: An OSF command-line library.
  description: An OSF command-line client and library.
  doc_url: http://osfclient.readthedocs.io/
  dev_url: https://github.com/dib-lab/osf-cli

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - darienmorrow
